### ISSUE TITLE
An Error occurred: Chunk exceeds the max length and contains no split characters.

### ISSUE THREAD

**Issue by Akouji** [AzuraApple/celestia#2]
Hello, thank you for the bot source code.

but i found a bug in **c.commands** if I type the command the bot will reply as follows:
- Sending commands to your DM ...
- An Error occurred: Chunk exceeds the max length and contains no split characters.

**Comment by PeachyTree** [comment]
Thank you, I'll take a look into it!
I don't have the time to actually check if every single command works, so I appreciate it.

**Comment by PeachyTree** [comment]
![image](https://user-images.githubusercontent.com/46896545/87026714-67ffba80-c1dc-11ea-9a50-d968c073f909.png)
Fixed!
