### ISSUE TITLE
NSFW Commands not working

### ISSUE THREAD

**Issue by aaaa888lol** [AzuraApple/celestia#5]
**Please describe the problem you are having in as much detail as possible:**
only nsfw command working is ass no other commanss work i just get a 404 error

**Further details:**
- Version:
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while self-hosting the bot.
  - Node.js version:
  - Commit hash:
  - Operating system:

**Comment by PeachyTree** [comment]
Hi, I will take a look into it later, thank you!

**Comment by PeachyTree** [comment]
Seems like it can't get the nsfw subreddits and that the status code is unavailable. Uhh that's not good, I'll try to find a different way.
