### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Marcel9089** [AzuraApple/celestia#7]
![Capture](https://user-images.githubusercontent.com/69435399/89843358-43756600-db2d-11ea-909c-c71fc47f83d4.PNG)
So my token is in a env file 
![Capture](https://user-images.githubusercontent.com/69435399/89843385-5ee07100-db2d-11ea-9c75-d938b9792815.PNG)
And it says invalid token it's currently stored like this 
CELESTIA_TOKEN=My discords bot token here.
And it doesn't work

**Comment by buttermiilk** [comment]
Did you add `const dotenv = require('dotenv')` , `const CELESTIA_TOKEN = process.env` and `client.login(CELESTIA_TOKEN)` to the main logging in logic file?

And by the way, you'll have to rename `dotenv.env` to `.env` if you want to run the bot with less errors (some files needs .env, like shorten.js). 
 If you're experiencing problems renaming files, try using a coding program and add the file manually (as I understand Windows won't let you have no name files).
