### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by SmokieTheDEV** [AzuraApple/celestia#8]
Oh no, an error occurred: fields.flat is not a function.
This is coming in help ,
Pls help.

**Comment by buttermiilk** [comment]
Update `node` to v12.x.
EDIT: do `node -v` to check node version. If on repl.it, add `.replit` with the following content: `language: "nodejs"`.
You can find various websites to update node on Google.

**Comment by PeachyTree** [comment]
@TheFateAkira Thanks for answering all the issues, I've been away on GitHub for a while.
